### PR TITLE
Support embed package

### PR DESCRIPTION
**Pull request by shuntagami**

### CODE REVIEW

**Comment by shuntagami** [comment]
@appleboy 
I moved PR from https://github.com/gin-contrib/i18n/pull/3 to here and add some changes to pass ci.
By the way, to fix the error for `Error: embed.go:4:2: package embed is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/embed)` we have to make supported go version >= 1.16 , embed package is supported. https://tip.golang.org/doc/go1.16#library-embed

**Comment by appleboy** [comment]
@shuntagami You can try build tag in golang to resolve the issue.

**Comment by shuntagami** [comment]
@appleboy OK, build tag added

**Comment by shuntagami** [comment]
@appleboy Please run the workflows

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
@shuntagami Thanks.

**Pull request merged**
